### ISSUE TITLE
Add Binary Search Algorithm

### ISSUE THREAD

**Issue by BugHunters-bug** [BugHunters-bug/AlgorithmBank#1]
Algorithms of Binary Search .

Rules:-
1. Make a seperate folder called Binary Search.
2. Add your algorithm as a file. 
3. You can use any programming language.

**Comment by Sid130698** [comment]
> Algorithms of Binary Search .
> 
> Rules:-
> 
> 1. Make a seperate folder called Binary Search.
> 2. Add your algorithm as a file.
> 3. You can use any programming language.

Please assign me this issue i would love to contribute

**Comment by iamkartikeysingh** [comment]
Assign me this. I would like to like to contibute.

**Comment by BugHunters-bug** [comment]
> Assign me this. I would like to contibute.

Please refer issue #2

**Comment by BugHunters-bug** [comment]
Great work @Sid130698.
