### ISSUE TITLE
Add Bubble Sort Algorithm

### ISSUE THREAD

**Issue by BugHunters-bug** [BugHunters-bug/AlgorithmBank#4]
Algorithms of Bubble Sort .

Rules:-

Make a separate folder called Bubble Sort.
Add your algorithm as a file.
You can use any programming language.

**Comment by iamkartikeysingh** [comment]
Please assign me this issue. I would like to contribute to this.

**Comment by YushChaudhary** [comment]
is it available?

**Comment by BugHunters-bug** [comment]
Create a new issue. If its approved, You can send a Pull request @YushChaudhary
