### ISSUE TITLE
KMP Algorithm for Pattern Searching

### ISSUE THREAD

**Issue by BugHunters-bug** [BugHunters-bug/AlgorithmBank#9]
KMP Alogorithm.

Refer:-https://www.geeksforgeeks.org/kmp-algorithm-for-pattern-searching/

Rules:-

Make a separate folder called KMP Algorithm.
Add your algorithm as a file.
You can use any programming language.

**Comment by Harshitha-sa** [comment]
Can I work on this?

**Comment by BugHunters-bug** [comment]
Sure,I will be assigning you.

**Comment by Harshitha-sa** [comment]
Completed please check #14

**Comment by BugHunters-bug** [comment]
Good
